In [ ]:
import numpy as np

arr1=np.array([1,2,3])
print(arr1)


2d array

In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

zeros only matrix

In [ ]:
import numpy as np
arr1=np.zeros((3,3))
print(arr1)

all values ones

In [ ]:
import numpy as np
arr1=np.ones((3,4))
print(arr1)

eye function (diagonal values 1)

In [ ]:
import numpy as np
arr1=np.eye(3)
print(len(arr1))
print(arr1)

arrange function (arranges values in range)

In [ ]:
import numpy as np
arr1=np.arange(100,0,-2)
print(arr1)

linespace function

In [30]:
import numpy as np 
arr1=np.linspace(1,7,22)
print(arr1)

[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.         3.28571429 3.57142857 3.85714286 4.14285714
 4.42857143 4.71428571 5.         5.28571429 5.57142857 5.85714286
 6.14285714 6.42857143 6.71428571 7.        ]


random.rand function (raandomize by uniform distributuion) values ranging from  0 to 1

In [75]:
import numpy as np
arr1=np.random.rand(3,3)
print(arr1)

[[0.31386253 0.19409771 0.53695157]
 [0.02752966 0.7426929  0.54373286]
 [0.93369139 0.25988815 0.35061702]]


random.randn function (randomize by normal distribution ) values ranging near to 0

In [76]:
import numpy as np
arr1=np.random.randn(3,2)
print(arr1)

[[-0.27921876  0.34647765]
 [-1.3242893   0.3230745 ]
 [-0.39373942 -1.00104217]]


array properties

In [85]:
import numpy as np
arr1=np.array([[2,3,1],[5,2,1]])
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)

(2, 3)
2
int64
6


Arithmetic Operations

In [88]:
import numpy as np
arr1=np.array([[5,3,2],[2,1,3],[7.,4,6]])
arr2=np.array([[0,6,2],[6,3,4],[8,6,4]])
print(arr1+arr2)
print()
print(arr1-arr2)
print()
print(np.dot(arr1,arr2))

[[ 5.  9.  4.]
 [ 8.  4.  7.]
 [15. 10. 10.]]

[[ 5. -3.  0.]
 [-4. -2. -1.]
 [-1. -2.  2.]]

[[34. 51. 30.]
 [30. 33. 20.]
 [72. 90. 54.]]


aggrgate functions 

In [99]:
import numpy as np
arr1=np.array([[5,3,2],[2,1,3],[7.,4,6]])
arr2=np.array([[0,6,2],[6,3,4],[8,6,4]])
print(np.sum(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print("max of arr1 is ",np.max(arr1))
print("max of arr2 is",np.max(arr2))
print("Min of arr1 is",int(np.min(arr1)))
print("Min of arr2 is",np.min(arr2))
print(np.std(arr2))

33.0
3.6666666666666665
3.0
max of arr1 is  7.0
max of arr2 is 8
Min of arr1 is 1
Min of arr2 is 0
2.309401076758503


indexing and slicing in numpy

In [103]:
import numpy as np
arr1=np.array([0,1,2,3,2,1,6,91,99928])
print(np.std(arr1))
print(arr1[::-1])

31400.18882619956
[99928    91     6     1     2     3     2     1     0]
